//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by resource.rc
//
#define IDD_DIALOG                      101
#define IDD_DIALOG_ABOUT                107
#define IDD_DIALOG_PE_EDITOR            134
#define IDD_DIALOG_IMAGE_FILE_HEADER    142
#define IDD_DIALOG_MACHINE_TYPE         144
#define IDD_DIALOG_CHARACTERISTICS      146
#define IDC_BUTTON_PE_EDITOR            1001
#define IDC_LIST_PROCESS                1008
#define IDC_BUTTON_PROFILE              1009
#define IDC_BUTTON_ABOUT                1009
#define IDC_BUTTON_QUIT                 1010
#define IDC_LIST_MODULE                 1011
#define IDC_GROUP_LIST                  1012
#define IDC_GROUP_BUTTON                1013
#define IDC_ABOUT_PIC                   1018
#define IDB_BITMAP_PEVIEWER             1018
#define IDC_BUTTON_OK                   1019
#define IDC_STATIC_                     1020
#define IDC_TEXT_7EVIEWER               1020
#define IDC_TEXT_INTRO                  1021
#define IDC_TEXT_CREATED                1022
#define IDC_TEXT_CREATOR                1023
#define IDC_GROUP_DOS_HEADER            1024
#define IDC_GROUP_INFO                  1025
#define IDC_BUTTON_FILE_HEADER          1026
#define IDC_BUTTON_OPTION_HEADER        1027
#define IDC_BUTTON_HEADER_INFO          1028
#define IDC_BUTTON_SECTION              1029
#define IDC_GROUP_TOOLS                 1030
#define IDC_BUTTON_DIRECTORY            1031
#define IDC_BUTTON_TOOLS                1032
#define IDC_GROUP_OK                    1033
#define IDC_BUTTON_EDIT                 1034
#define IDC_BUTTON_DOS_OK               1034
#define IDC_BUTTON_CANCEL               1035
#define IDC_BUTTON_DOS_CANCEL           1035
#define IDC_STATIC_MAGIC_NUMBER         1036
#define IDC_STATIC_BLG                  1037
#define IDC_STATIC_BLP                  1037
#define IDC_EDIT_MAGIC_NUMBER           1038
#define IDC_STATIC_CHECKSUM             1039
#define IDC_EDIT_CHECKSUM               1040
#define IDC_EDIT_BLG                    1041
#define IDC_EDIT_BLP                    1041
#define IDC_STATIC_PAGES                1042
#define IDC_EDIT_PAGES                  1043
#define IDC_STATIC_RLC                  1044
#define IDC_EDIT_RLC                    1045
#define IDC_STATIC_PARHDR               1046
#define IDC_STATIC_MACHINE              1046
#define IDC_EDIT_PARHDR                 1047
#define IDC_EDIT_MACHINE                1047
#define IDC_STATIC_MIN_ALLOC            1048
#define IDC_STATIC_NUMBER_OF_SECTIONS   1048
#define IDC_EDIT_MIN_ALLOC              1049
#define IDC_EDIT_NUMBER_OF_SECTIONS     1049
#define IDC_STATIC_MAX_ALLOC            1050
#define IDC_STATIC_TIMEDATESTAMP        1050
#define IDC_EDIT_MAX_ALLOC              1051
#define IDC_EDIT_TIMEDATESTAMP          1051
#define IDC_STATIC_INIT_SS              1052
#define IDC_STATIC_P_SYMTAB             1052
#define IDC_EDIT_INIT_SS                1053
#define IDC_EDIT_P_SYMTAB               1053
#define IDC_STATIC_INIT_SP              1054
#define IDC_STATIC_SIZE_OF_OPT_HEADER   1054
#define IDC_EDIT_INIT_SP                1055
#define IDC_EDIT_SIZE_OF_OPT_HEADER     1055
#define IDC_STATIC_INIT_IP              1056
#define IDC_STATIC_CHARACTERISTICS      1056
#define IDC_EDIT_INIT_IP                1057
#define IDC_EDIT_CHARACTERISTICS        1057
#define IDC_STATIC_INIT_CS              1058
#define IDC_EDIT_INIT_CS                1059
#define IDC_BUTTON_MACHINE              1059
#define IDC_BUTTON_FILE_HEADER_MACHINE  1059
#define IDC_STATIC_LFARLC               1060
#define IDC_STATIC_NUMBER_OF_SYMBOL     1060
#define IDC_EDIT_LFARLC                 1061
#define IDC_EDIT_NUMBER_OF_SYMBOL       1061
#define IDC_STATIC_OVNO                 1062
#define IDC_BUTTON_TIMEDATESTAMP        1062
#define IDC_BUTTON_FILE_HEADER_TIMEDATESTAMP 1062
#define IDC_EDIT_OVNO                   1063
#define IDC_BUTTON_CHARACTERISTICS      1063
#define IDC_BUTTON_FILE_HEADER_CHARACTERISTICS 1063
#define IDC_STATIC_OEM_ID               1064
#define IDC_BUTTON_FILE_HEADER_OK       1064
#define IDC_EDIT_OEM_ID                 1065
#define IDC_BUTTON_FILE_HEADER_CANCEL   1065
#define IDC_STATIC_OEM_INFO             1066
#define IDC_GROUP_MACHINE_TYPE          1066
#define IDC_EDIT_OEM_INFO               1067
#define IDC_STATIC_PE_ADDRESS           1068
#define IDC_EDIT_OEM_INFO2              1069
#define IDC_EDIT_PE_ADDRESS             1069
#define IDC_COMBO1                      1069
#define IDC_COMBO_MACHINE_TYPE          1069
#define IDC_BUTTON_MACHINE_TYPE_OK      1070
#define IDC_BUTTON_MACHINE_TYPE_CANCEL  1071
#define IDC_CHECK_FILE_RELOCS_STRIPPED  1072
#define IDC_CHECK_FILE_EXECUTABLE_IMAGE 1073
#define IDC_CHECK_FILE_LINE_NUMS_STRIPPED 1074
#define IDC_CHECK_FILE_LOCAL_SYMS_STRIPPED 1075
#define IDC_CHECK_FILE_AGGRESSIVE_WS_TRIM 1076
#define IDC_CHECK_FILE_LARGE_ADDRESS_AWARE 1077
#define IDC_CHECK_CHARA_RESERVED        1078
#define IDC_CHECK_FILE_BYTES_REVERSED_LO 1079
#define IDC_CHECK_FILE_32BIT_MACHINE    1080
#define IDC_CHECK_FILE_DEBUG_STRIPPED   1081
#define IDC_CHECK_FILE_REMOVABLE_RUN_FROM_SWAP 1082
#define IDC_CHECK_FILE_NET_RUN_FROM_SWAP 1083
#define IDC_CHECK_FILE_SYSTEM           1084
#define IDC_CHECK_FILE_DLL              1085
#define IDC_CHECK_FILE_UP_SYSTEM_ONLY   1086
#define IDC_CHECK16                     1087
#define IDC_CHECK_FILE_BYTES_REVERSED_HI 1087
#define IDC_BUTTON_CHARACTERISTICS_OK   1088
#define IDC_BUTTON_CHARACTERISTICS_CANCEL 1089

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
